name: CI Pipeline

on:
  workflow_dispatch:

  push:
      branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    paths:
    - 'cmd/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - 'Makefile'
    - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' 
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=15m
      
      - name: Run tests
        run: make test
      
      - name: Log in to the Github Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      