name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  test-and-lint:
    name: Lint & Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=15m

      - name: Run tests
        run: make test

  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: test-and-lint
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY}" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPO }}:latest
          

      