name: CI Pipeline

on:
  workflow_dispatch:

  push:
      branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    paths:
    - 'cmd/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - 'Makefile'
    - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' 

      - name: Run tests
        run: make test

      